/**
 * VRChat API Documentation
 * ![VRChat API Banner](https://raw.githubusercontent.com/vrchatapi/vrchatapi.github.io/master/assets/apibanner.png)  # VRChat API Documentation This project is an [OPEN Open Source Project](https://openopensource.org)  Individuals making significant and valuable contributions are given commit-access to the project to contribute as they see fit. This project is more like an open wiki than a standard guarded open source project.  ## Disclaimer  This is the official response of the VRChat Team (from Tupper more specifically) on the usage of the VRChat API.  > **Use of the API using applications other than the approved methods (website, VRChat application) are not officially supported. You may use the API for your own application, but keep these guidelines in mind:** > * We do not provide documentation or support for the API. > * Do not make queries to the API more than once per 60 seconds. > * Abuse of the API may result in account termination. > * Access to API endpoints may break at any given time, with no warning.  As stated, this documentation was not created with the help of the official VRChat team. Therefore this documentation is not an official documentation of the VRChat API and may not be always up to date with the latest versions. If you find that a page or endpoint is not longer valid please create an issue and tell us so we can fix it.  ## Get in touch with us!  [https://discord.gg/qjZE9C9fkB#vrchat-api](https://discord.gg/qjZE9C9fkB)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: me@ruby.js.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ConfigEvents model module.
 * @module model/ConfigEvents
 * @version 1.0.0
 */
class ConfigEvents {
    /**
     * Constructs a new <code>ConfigEvents</code>.
     * @alias module:model/ConfigEvents
     * @param distanceClose {Number} Unknown
     * @param distanceFactor {Number} Unknown
     * @param distanceFar {Number} Unknown
     * @param groupDistance {Number} Unknown
     * @param maximumBunchSize {Number} Unknown
     * @param notVisibleFactor {Number} Unknown
     * @param playerOrderBucketSize {Number} Unknown
     * @param playerOrderFactor {Number} Unknown
     * @param slowUpdateFactorThreshold {Number} Unknown
     * @param viewSegmentLength {Number} Unknown
     */
    constructor(distanceClose, distanceFactor, distanceFar, groupDistance, maximumBunchSize, notVisibleFactor, playerOrderBucketSize, playerOrderFactor, slowUpdateFactorThreshold, viewSegmentLength) { 
        
        ConfigEvents.initialize(this, distanceClose, distanceFactor, distanceFar, groupDistance, maximumBunchSize, notVisibleFactor, playerOrderBucketSize, playerOrderFactor, slowUpdateFactorThreshold, viewSegmentLength);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, distanceClose, distanceFactor, distanceFar, groupDistance, maximumBunchSize, notVisibleFactor, playerOrderBucketSize, playerOrderFactor, slowUpdateFactorThreshold, viewSegmentLength) { 
        obj['distanceClose'] = distanceClose;
        obj['distanceFactor'] = distanceFactor;
        obj['distanceFar'] = distanceFar;
        obj['groupDistance'] = groupDistance;
        obj['maximumBunchSize'] = maximumBunchSize;
        obj['notVisibleFactor'] = notVisibleFactor;
        obj['playerOrderBucketSize'] = playerOrderBucketSize;
        obj['playerOrderFactor'] = playerOrderFactor;
        obj['slowUpdateFactorThreshold'] = slowUpdateFactorThreshold;
        obj['viewSegmentLength'] = viewSegmentLength;
    }

    /**
     * Constructs a <code>ConfigEvents</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConfigEvents} obj Optional instance to populate.
     * @return {module:model/ConfigEvents} The populated <code>ConfigEvents</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConfigEvents();

            if (data.hasOwnProperty('distanceClose')) {
                obj['distanceClose'] = ApiClient.convertToType(data['distanceClose'], 'Number');
            }
            if (data.hasOwnProperty('distanceFactor')) {
                obj['distanceFactor'] = ApiClient.convertToType(data['distanceFactor'], 'Number');
            }
            if (data.hasOwnProperty('distanceFar')) {
                obj['distanceFar'] = ApiClient.convertToType(data['distanceFar'], 'Number');
            }
            if (data.hasOwnProperty('groupDistance')) {
                obj['groupDistance'] = ApiClient.convertToType(data['groupDistance'], 'Number');
            }
            if (data.hasOwnProperty('maximumBunchSize')) {
                obj['maximumBunchSize'] = ApiClient.convertToType(data['maximumBunchSize'], 'Number');
            }
            if (data.hasOwnProperty('notVisibleFactor')) {
                obj['notVisibleFactor'] = ApiClient.convertToType(data['notVisibleFactor'], 'Number');
            }
            if (data.hasOwnProperty('playerOrderBucketSize')) {
                obj['playerOrderBucketSize'] = ApiClient.convertToType(data['playerOrderBucketSize'], 'Number');
            }
            if (data.hasOwnProperty('playerOrderFactor')) {
                obj['playerOrderFactor'] = ApiClient.convertToType(data['playerOrderFactor'], 'Number');
            }
            if (data.hasOwnProperty('slowUpdateFactorThreshold')) {
                obj['slowUpdateFactorThreshold'] = ApiClient.convertToType(data['slowUpdateFactorThreshold'], 'Number');
            }
            if (data.hasOwnProperty('viewSegmentLength')) {
                obj['viewSegmentLength'] = ApiClient.convertToType(data['viewSegmentLength'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Unknown
 * @member {Number} distanceClose
 */
ConfigEvents.prototype['distanceClose'] = undefined;

/**
 * Unknown
 * @member {Number} distanceFactor
 */
ConfigEvents.prototype['distanceFactor'] = undefined;

/**
 * Unknown
 * @member {Number} distanceFar
 */
ConfigEvents.prototype['distanceFar'] = undefined;

/**
 * Unknown
 * @member {Number} groupDistance
 */
ConfigEvents.prototype['groupDistance'] = undefined;

/**
 * Unknown
 * @member {Number} maximumBunchSize
 */
ConfigEvents.prototype['maximumBunchSize'] = undefined;

/**
 * Unknown
 * @member {Number} notVisibleFactor
 */
ConfigEvents.prototype['notVisibleFactor'] = undefined;

/**
 * Unknown
 * @member {Number} playerOrderBucketSize
 */
ConfigEvents.prototype['playerOrderBucketSize'] = undefined;

/**
 * Unknown
 * @member {Number} playerOrderFactor
 */
ConfigEvents.prototype['playerOrderFactor'] = undefined;

/**
 * Unknown
 * @member {Number} slowUpdateFactorThreshold
 */
ConfigEvents.prototype['slowUpdateFactorThreshold'] = undefined;

/**
 * Unknown
 * @member {Number} viewSegmentLength
 */
ConfigEvents.prototype['viewSegmentLength'] = undefined;






export default ConfigEvents;

